// Additional mock data for blog/news
export const mockPosts = [
    {
        id: '1',
        title: 'Xu hướng công nghệ xử lý nước thải năm 2026',
        slug: 'xu-huong-cong-nghe-xu-ly-nuoc-thai-2026',
        excerpt: 'Tìm hiểu về các công nghệ xử lý nước thải tiên tiến đang được áp dụng rộng rãi tại Việt Nam',
        content: 'Nội dung chi tiết về xu hướng công nghệ xử lý nước thải...',
        category: 'Công nghệ',
        author: 'Nguyễn Văn A',
        date: '2026-02-01',
        publishedDate: '2026-02-01',
        image: '/placeholders/blog-1.jpg',
        featuredImageUrl: '/placeholders/blog-1.jpg',
        tags: ['Xử lý nước', 'Công nghệ', 'Môi trường'],
        readTime: '5 phút đọc',
    },
    {
        id: '2',
        title: 'Hướng dẫn bảo trì hệ thống cấp nước định kỳ',
        slug: 'huong-dan-bao-tri-he-thong-cap-nuoc',
        excerpt: 'Quy trình bảo trì hệ thống cấp nước để đảm bảo hoạt động ổn định lâu dài',
        content: 'Nội dung hướng dẫn bảo trì hệ thống cấp nước...',
        category: 'Hướng dẫn',
        author: 'Trần Thị B',
        date: '2026-01-28',
        publishedDate: '2026-01-28',
        image: '/placeholders/blog-2.jpg',
        featuredImageUrl: '/placeholders/blog-2.jpg',
        tags: ['Bảo trì', 'Cấp nước', 'Hướng dẫn'],
        readTime: '7 phút đọc',
    },
    {
        id: '3',
        title: 'Tiêu chuẩn QCVN về xử lý nước thải công nghiệp',
        slug: 'tieu-chuan-qcvn-xu-ly-nuoc-thai',
        excerpt: 'Tổng hợp các tiêu chuẩn QCVN hiện hành về xử lý nước thải công nghiệp tại Việt Nam',
        content: 'Nội dung về tiêu chuẩn QCVN...',
        category: 'Quy định',
        author: 'Lê Văn C',
        date: '2026-01-25',
        publishedDate: '2026-01-25',
        image: '/placeholders/blog-3.jpg',
        featuredImageUrl: '/placeholders/blog-3.jpg',
        tags: ['Quy định', 'QCVN', 'Xử lý nước thải'],
        readTime: '10 phút đọc',
    },
    {
        id: '4',
        title: 'So sánh các loại máy bơm cấp nước phổ biến',
        slug: 'so-sanh-cac-loai-may-bom-cap-nuoc',
        excerpt: 'Phân tích ưu nhược điểm của các loại máy bơm cấp nước được sử dụng nhiều nhất',
        content: 'Nội dung so sánh các loại máy bơm...',
        category: 'Sản phẩm',
        author: 'Phạm Thị D',
        date: '2026-01-20',
        publishedDate: '2026-01-20',
        image: '/placeholders/blog-4.jpg',
        featuredImageUrl: '/placeholders/blog-4.jpg',
        tags: ['Máy bơm', 'Cấp nước', 'So sánh'],
        readTime: '6 phút đọc',
    },
]
