// Mock data for development - will be replaced with database queries later

export const mockCategories = [
    {
        id: '1',
        name: 'Thiết bị Cơ Điện',
        slug: 'thiet-bi-co-dien',
        description: 'Thiết bị M&E cho công trình dân dụng và công nghiệp',
        icon: 'Zap',
    },
    {
        id: '2',
        name: 'Thiết bị Cấp Nước',
        slug: 'thiet-bi-cap-nuoc',
        description: 'Hệ thống cấp nước sạch và phân phối',
        icon: 'Droplet',
    },
    {
        id: '3',
        name: 'Thiết bị Xử Lý Nước',
        slug: 'thiet-bi-xu-ly-nuoc',
        description: 'Hệ thống xử lý nước thải và nước sạch',
        icon: 'Waves',
    },
]

export const mockProducts = [
    {
        id: '1',
        name: 'Máy bơm ly tâm Grundfos CR 3-36',
        slug: 'may-bom-ly-tam-grundfos-cr-3-36',
        description: 'Máy bơm ly tâm đa tầng cánh Grundfos CR, phù hợp cho hệ thống cấp nước, tăng áp',
        technicalSpecifications: [
            { parameter: 'Lưu lượng', value: '3', unit: 'm³/h' },
            { parameter: 'Cột áp', value: '36', unit: 'm' },
            { parameter: 'Công suất', value: '1.5', unit: 'kW' },
            { parameter: 'Điện áp', value: '380', unit: 'V' },
        ],
        price: 15500000,
        stock: 5,
        sku: 'GRF-CR3-36',
        categoryId: '2',
        category: 'Thiết bị Cấp Nước',
        images: ['/placeholders/pump-1.jpg'],
        featured: true,
        rating: 5,
    },
    {
        id: '2',
        name: 'Hệ thống lọc nước RO công nghiệp 500L/h',
        slug: 'he-thong-loc-nuoc-ro-500l',
        description: 'Hệ thống lọc nước RO công nghiệp, công suất 500 lít/giờ',
        technicalSpecifications: [
            { parameter: 'Công suất', value: '500', unit: 'L/h' },
            { parameter: 'Số màng RO', value: '4', unit: 'cái' },
            { parameter: 'Áp lực hoạt động', value: '3-8', unit: 'bar' },
            { parameter: 'Tỷ lệ thu hồi', value: '60', unit: '%' },
        ],
        price: 45000000,
        stock: 2,
        sku: 'RO-500L-IND',
        categoryId: '3',
        category: 'Thiết bị Xử Lý Nước',
        images: ['/placeholders/ro-system.jpg'],
        featured: true,
        rating: 4.5,
    },
    {
        id: '3',
        name: 'Máy bơm chìm Ebara 3M 32-160',
        slug: 'may-bom-chim-ebara-3m-32-160',
        description: 'Máy bơm chìm hố móng Ebara, phù hợp cho thoát nước ngầm, công trình xây dựng',
        technicalSpecifications: [
            { parameter: 'Lưu lượng', value: '8', unit: 'm³/h' },
            { parameter: 'Cột áp', value: '20', unit: 'm' },
            { parameter: 'Công suất', value: '0.75', unit: 'kW' },
        ],
        price: 8900000,
        stock: 10,
        sku: 'EBR-3M32-160',
        categoryId: '2',
        category: 'Thiết bị Cấp Nước',
        images: ['/placeholders/pump-2.jpg'],
        featured: true,
        rating: 4.8,
    },
    {
        id: '4',
        name: 'Biến tần bơm nước Schneider ATV320',
        slug: 'bien-tan-bom-nuoc-schneider-atv320',
        description: 'Biến tần điều khiển tốc độ động cơ bơm nước, tiết kiệm năng lượng, bảo vệ quá tải',
        technicalSpecifications: [
            { parameter: 'Công suất', value: '2.2-7.5', unit: 'kW' },
            { parameter: 'Điện áp vào', value: '3 pha 380V', unit: '' },
            { parameter: 'Tần số', value: '0-60', unit: 'Hz' },
            { parameter: 'Hiệu suất', value: '≥ 95', unit: '%' },
        ],
        price: 12800000,
        stock: 8,
        sku: 'SCH-ATV320-2.2',
        categoryId: '1',
        category: 'Thiết bị Cơ Điện',
        images: ['/placeholders/inverter.jpg'],
        featured: true,
        rating: 4.7,
    },
    {
        id: '5',
        name: 'Van điện từ ASCO 8210 Series',
        slug: 'van-dien-tu-asco-8210',
        description: 'Van điện từ điều khiển dòng chảy nước, áp dụng cho hệ thống cấp nước tự động',
        technicalSpecifications: [
            { parameter: 'Đường kính', value: 'DN50', unit: '' },
            { parameter: 'Áp suất', value: '0-10', unit: 'bar' },
            { parameter: 'Điện áp', value: '220VAC', unit: '' },
            { parameter: 'Vật liệu', value: 'Inox 304', unit: '' },
        ],
        price: 3200000,
        stock: 15,
        sku: 'ASCO-8210-DN50',
        categoryId: '1',
        category: 'Thiết bị Cơ Điện',
        images: ['/placeholders/valve.jpg'],
        featured: true,
        rating: 4.6,
    },
    {
        id: '6',
        name: 'Bộ lọc nước sinh hoạt 3 cấp Aqua',
        slug: 'bo-loc-nuoc-sinh-hoat-3-cap-aqua',
        description: 'Bộ lọc nước sinh hoạt 3 cấp lọc, loại bỏ cặn bẩn, mùi vị, vi khuẩn',
        technicalSpecifications: [
            { parameter: 'Công suất lọc', value: '15', unit: 'L/phút' },
            { parameter: 'Số lõi lọc', value: '3', unit: 'cấp' },
            { parameter: 'Áp lực nước', value: '1-4', unit: 'bar' },
            { parameter: 'Kích thước', value: '35 x 14 x 42', unit: 'cm' },
        ],
        price: 2500000,
        stock: 20,
        sku: 'AQUA-3F-15L',
        categoryId: '3',
        category: 'Thiết bị Xử Lý Nước',
        images: ['/placeholders/filter.jpg'],
        featured: true,
        rating: 4.9,
    },
]

export const mockProjects = [
    {
        id: '1',
        title: 'Hệ thống xử lý nước thải - Khu công nghiệp Tân Bình',
        slug: 'he-thong-xu-ly-nuoc-thai-kcn-tan-binh',
        description: 'Thi công lắp đặt hệ thống xử lý nước thải công suất 1000m³/ngày',
        technicalDetails: 'Công nghệ xử lý: AAO + MBR. Công suất: 1000m³/ngày. Tiêu chuẩn đầu ra: QCVN 40:2011/BTNMT',
        location: 'Khu công nghiệp Tân Bình, TP.HCM',
        client: 'Công ty TNHH ABC Manufacturing',
        completionDate: '2025-06-15',
        category: 'Xử lý nước thải',
        images: ['/placeholders/project-1.jpg'],
        featured: true,
    },
    {
        id: '2',
        title: 'Hệ thống cấp nước - Chung cư Vinhomes Grand Park',
        slug: 'he-thong-cap-nuoc-chung-cu-vinhomes',
        description: 'Lắp đặt hệ thống cấp nước, tăng áp cho chung cư 30 tầng',
        technicalDetails: 'Hệ thống bơm tăng áp biến tần Grundfos Hydro MPC, công suất 150m³/h, 500+ căn hộ',
        location: 'Vinhomes Grand Park, Quận 9, TP.HCM',
        client: 'Vingroup',
        completionDate: '2025-08-20',
        category: 'Cấp nước',
        images: ['/placeholders/project-2.jpg'],
        featured: true,
    },
    {
        id: '3',
        title: 'Hệ thống PCCC - Tòa nhà văn phòng Lotte Center',
        slug: 'he-thong-pccc-toa-nha-lotte',
        description: 'Thiết kế, thi công hệ thống phòng cháy chữa cháy tòa nhà 25 tầng',
        technicalDetails: 'Hệ thống sprinkler tự động, bơm PCCC Pentax 300m³/h, báo cháy địa chỉ',
        location: 'Quận 7, TP.HCM',
        client: 'Lotte Vietnam',
        completionDate: '2025-03-10',
        category: 'Cơ điện',
        images: ['/placeholders/project-3.jpg'],
        featured: true,
    },
]

export const mockServices = [
    {
        id: '1',
        title: 'Tư vấn thiết kế hệ thống M&E',
        slug: 'tu-van-thiet-ke-he-thong-me',
        description: 'Dịch vụ tư vấn, thiết kế hệ thống cơ điện cho công trình dân dụng và công nghiệp',
        icon: 'Lightbulb',
        features: [
            'Khảo sát hiện trạng công trình',
            'Thiết kế bản vẽ kỹ thuật chi tiết',
            'Tính toán phương án tối ưu',
            'Lập dự toán chi tiết',
            'Hỗ trợ thẩm duyệt hồ sơ',
        ],
    },
    {
        id: '2',
        title: 'Lắp đặt hệ thống cấp thoát nước',
        slug: 'lap-dat-he-thong-cap-thoat-nuoc',
        description: 'Thi công lắp đặt hệ thống cấp nước, thoát nước cho mọi loại công trình',
        icon: 'Wrench',
        features: [
            'Lắp đặt đường ống cấp thoát nước',
            'Lắp đặt thiết bị bơm tăng áp',
            'Thử nghiệm hệ thống theo TCVN',
            'Bảo hành 24 tháng',
            'Bảo trì định kỳ',
        ],
    },
    {
        id: '3',
        title: 'Vận hành & bảo trì hệ thống',
        slug: 'van-hanh-bao-tri-he-thong',
        description: 'Dịch vụ vận hành và bảo trì hệ thống xử lý nước chuyên nghiệp',
        icon: 'Settings',
        features: [
            'Vận hành hệ thống 24/7',
            'Bảo trì định kỳ theo lịch',
            'Cung cấp hóa chất xử lý',
            'Giám sát chất lượng nước',
            'Báo cáo định kỳ',
        ],
    },
    {
        id: '4',
        title: 'Sửa chữa & nâng cấp',
        slug: 'sua-chua-nang-cap',
        description: 'Sửa chữa, cải tạo và nâng cấp các hệ thống hiện có',
        icon: 'Hammer',
        features: [
            'Đánh giá hiện trạng hệ thống',
            'Đề xuất giải pháp tối ưu',
            'Thay thế thiết bị cũ',
            'Nâng cấp công nghệ mới',
            'Tối ưu hiệu suất vận hành',
        ],
    },
]

export const mockTestimonials = [
    {
        id: '1',
        clientName: 'Trần Văn Bình',
        clientPosition: 'Giám đốc kỹ thuật',
        clientCompany: 'Công ty TNHH XYZ Manufacturing',
        testimonial: 'Siphonet đã hỗ trợ chúng tôi rất tận tình trong dự án xử lý nước thải. Chất lượng thi công tốt, tiến độ đúng cam kết, đội ngũ kỹ thuật chuyên nghiệp.',
        rating: 5,
        featured: true,
    },
    {
        id: '2',
        clientName: 'Nguyễn Thị Hương',
        clientPosition: 'Quản lý dự án',
        clientCompany: 'Vingroup',
        testimonial: 'Hệ thống cấp nước do Siphonet lắp đặt vận hành rất ổn định. Đội ngũ hỗ trợ nhanh chóng, chuyên nghiệp.',
        rating: 5,
        featured: true,
    },
    {
        id: '3',
        clientName: 'Lê Minh Tuấn',
        clientPosition: 'Chủ đầu tư',
        clientCompany: 'Công ty CP Lotte Việt Nam',
        testimonial: 'Thiết kế hệ thống PCCC rất chuyên nghiệp, đáp ứng đầy đủ các tiêu chuẩn. Giá cả hợp lý, thi công đúng tiến độ.',
        rating: 5,
        featured: false,
    },
]

export const mockFAQs = [
    {
        id: '1',
        question: 'Siphonet cung cấp những thiết bị gì?',
        answer: 'Siphonet chuyên cung cấp thiết bị cơ điện (M&E), thiết bị cấp nước, thiết bị xử lý nước cho công trình dân dụng và công nghiệp. Chúng tôi là đại lý chính thức của nhiều thương hiệu nổi tiếng như Grundfos, Ebara, Pentax...',
        category: 'General',
        featured: true,
    },
    {
        id: '2',
        question: 'Thời gian bảo hành sản phẩm là bao lâu?',
        answer: 'Thời gian bảo hành tiêu chuẩn là 12-24 tháng tùy theo sản phẩm và hãng sản xuất. Một số sản phẩm cao cấp có thể có bảo hành lên đến 36 tháng. Chúng tôi cũng cung cấp dịch vụ bảo trì định kỳ sau thời gian bảo hành.',
        category: 'Products',
        featured: true,
    },
    {
        id: '3',
        question: 'Siphonet có thi công cho dự án nhỏ không?',
        answer: 'Có. Chúng tôi nhận thi công cho mọi quy mô dự án, từ nhà ở dân dụng đến các công trình công nghiệp lớn. Đội ngũ kỹ thuật của chúng tôi sẽ khảo sát và tư vấn giải pháp phù hợp nhất.',
        category: 'Services',
        featured: true,
    },
    {
        id: '4',
        question: 'Làm thế nào để đặt hàng?',
        answer: 'Bạn có thể đặt hàng trực tiếp trên website, hoặc liên hệ hotline/Zalo để được tư vấn. Chúng tôi hỗ trợ nhiều hình thức thanh toán: chuyển khoản, COD, hoặc thanh toán qua PayOS.',
        category: 'Payment',
        featured: false,
    },
]
