
const dotenv = require('dotenv')
dotenv.config({ path: '.env.local' })

if (!process.env.DATABASE_URL) {
    console.error('❌ DATABASE_URL not found in .env.local')
    process.exit(1)
}

const { db } = require('./index')
const { posts: postsTable } = require('./schema')
const { randomUUID } = require('crypto')

async function seed() {
    console.log('🌱 Seeding 25 mock posts...')

    const mockPosts = [
        // CATEGORY: Công ty
        { id: randomUUID(), title: 'Siphonet kỷ niệm 15 năm hình thành và phát triển', slug: 'kỷ-niệm-15-năm-thành-lập', excerpt: 'Hành trình 15 năm dẫn đầu lĩnh vực cơ điện và xử lý nước.', content: '<h1>Hành trình 15 năm đầy tự hào</h1><p>Công ty Siphonet vừa tổ chức lễ kỷ niệm 15 năm.</p>', category: 'Công ty', featuredImageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1200', author: 'Siphonet Admin', status: 'published', publishedDate: new Date('2024-01-15'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Bàn giao hệ thống xử lý nước thải KCN Quang Châu', slug: 'ban-giao-he-thong-quang-chau', excerpt: 'Dự án công suất 5000m3/ngày đêm đã đi vào hoạt động.', content: '<h1>Dự án trọng điểm tại Bắc Giang</h1>', category: 'Công ty', featuredImageUrl: 'https://images.unsplash.com/photo-1541888941255-081bbad96c30?q=80&w=1200', author: 'Siphonet Admin', status: 'published', publishedDate: new Date('2024-02-10'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Teambuilding 2024: "Kết sức mạnh - Nối thành công"', slug: 'teambuilding-2024', excerpt: 'Chuyến đi gắn kết đại gia đình Siphonet tại Đà Nẵng.', content: '<p>Hoạt động teambuilding hàng năm.</p>', category: 'Công ty', featuredImageUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?q=80&w=1200', author: 'Siphonet Admin', status: 'published', publishedDate: new Date('2024-03-20'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Siphonet nhận giải Doanh nghiệp Cơ điện tiêu biểu', slug: 'giai-thuong-co-dien-tieu-bieu', excerpt: 'Sự ghi nhận cho nỗ lực cải tiến chất lượng dịch vụ.', content: '<p>Giải thưởng do Hiệp hội Cơ điện trao tặng.</p>', category: 'Công ty', featuredImageUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?q=80&w=1200', author: 'Siphonet Admin', status: 'published', publishedDate: new Date('2023-12-25'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Khai trương văn phòng đại diện tại TP. Hồ Chí Minh', slug: 'khai-truong-chi-nhanh-hcm', excerpt: 'Mở rộng quy mô phục vụ khách hàng Miền Nam.', content: '<p>Văn phòng mới tại Quận 1.</p>', category: 'Công ty', featuredImageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200', author: 'Siphonet Admin', status: 'published', publishedDate: new Date('2024-04-05'), createdAt: new Date(), updatedAt: new Date() },

        // CATEGORY: Tuyển dụng
        { id: randomUUID(), title: 'Tuyển Kỹ sư Thiết kế M&E (Điện/Nước)', slug: 'tuyen-ky-su-me', excerpt: 'Gia nhập đội ngũ tài năng với phúc lợi hấp dẫn.', content: '<h3>Mô tả công việc</h3>', category: 'Tuyển dụng', featuredImageUrl: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?q=80&w=1200', author: 'HR Dept', status: 'published', publishedDate: new Date('2024-05-01'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Tuyển Kỹ thuật viên Vận hành Trạm nước', slug: 'tuyen-ktv-van-hanh', excerpt: 'Làm việc trực tiếp với hệ thống xử lý nước hiện đại.', content: '<p>Yêu cầu chuyên ngành môi trường.</p>', category: 'Tuyển dụng', featuredImageUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1200', author: 'HR Dept', status: 'published', publishedDate: new Date('2024-05-02'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Tuyển Nhân viên Kinh doanh Dự án B2B', slug: 'tuyen-sales-du-an', excerpt: 'Thu nhập hấp dẫn dành cho người am hiểu kỹ thuật.', content: '<p>Đam mê kinh doanh, am hiểu sản phẩm.</p>', category: 'Tuyển dụng', featuredImageUrl: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=1200', author: 'HR Dept', status: 'published', publishedDate: new Date('2024-05-03'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Chương trình Thực tập sinh NextGen 2024', slug: 'thuc-tap-sinh-2024', excerpt: 'Môi trường thực chiến cho sinh viên khối kỹ thuật.', content: '<p>Cơ hội trở thành nhân viên chính thức.</p>', category: 'Tuyển dụng', featuredImageUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=1200', author: 'HR Dept', status: 'published', publishedDate: new Date('2024-05-04'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Tuyển Trưởng phòng Dự án M&E', slug: 'tuyen-tp-du-an', excerpt: 'Vị trí lãnh đạo then chốt cho quản lý dày dạn.', content: '<p>Quản lý các tổng thầu lớn.</p>', category: 'Tuyển dụng', featuredImageUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=1200', author: 'HR Dept', status: 'published', publishedDate: new Date('2024-05-05'), createdAt: new Date(), updatedAt: new Date() },

        // CATEGORY: Công nghệ
        { id: randomUUID(), title: 'Giải pháp tiết kiệm năng lượng HVAC', slug: 'tiet-kiem-nang-luong-hvac', excerpt: 'Ứng dụng biến tần thông minh giảm 30% điện năng.', content: '<p>Tối ưu chiller theo tải thực tế.</p>', category: 'Công nghệ', featuredImageUrl: 'https://images.unsplash.com/photo-1558389186-438424b00a32?q=80&w=1200', author: 'Tech Lab', status: 'published', publishedDate: new Date('2024-04-15'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Công nghệ lọc màng UF tái sử dụng nước', slug: 'cong-nghe-uf-tai-su-dung', excerpt: 'Nước đạt chuẩn tưới cây và làm mát công nghiệp.', content: '<p>Loại bỏ vi khuẩn bằng lọc màng UF.</p>', category: 'Công nghệ', featuredImageUrl: 'https://images.unsplash.com/photo-1584622781564-1d9876a13d01?q=80&w=1200', author: 'Tech Lab', status: 'published', publishedDate: new Date('2024-04-16'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Hệ thống Smart Water Management 4.0', slug: 'smart-water-4-0', excerpt: 'Giám sát lưu lượng, chất lượng nước qua App.', content: '<p>Tích hợp IoT giám sát thời gian thực.</p>', category: 'Công nghệ', featuredImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200', author: 'Tech Lab', status: 'published', publishedDate: new Date('2024-04-17'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Tự động hóa trạm bơm cấp nước đô thị', slug: 'tu-dong-hoa-tram-bom', excerpt: 'Nâng cao độ an toàn cho hạ tầng đô thị.', content: '<p>Tích hợp SCADA vận hành tự động.</p>', category: 'Công nghệ', featuredImageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=1200', author: 'Tech Lab', status: 'published', publishedDate: new Date('2024-04-18'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Vật liệu composite cho bồn lọc áp lực', slug: 'vât-lieu-composite-bon-loc', excerpt: 'Trọng lượng nhẹ, chống ăn mòn hóa chất cực tốt.', content: '<p>Ứng dụng sợi thủy tinh cao cấp.</p>', category: 'Công nghệ', featuredImageUrl: 'https://images.unsplash.com/photo-1535813543269-7328ad13954f?q=80&w=1200', author: 'Tech Lab', status: 'published', publishedDate: new Date('2024-04-19'), createdAt: new Date(), updatedAt: new Date() },

        // CATEGORY: Chuyên ngành
        { id: randomUUID(), title: 'Cập nhật tiêu chuẩn PCCC năm 2024', slug: 'tieu-chuan-pccc-2024', excerpt: 'Những thay đổi quan trọng chủ đầu tư cần lưu ý.', content: '<p>Nghị định 50 mới bổ sung yêu cầu kỹ thuật.</p>', category: 'Chuyên ngành', featuredImageUrl: 'https://images.unsplash.com/photo-1516567727245-ad8c68f3ec93?q=80&w=1200', author: 'Engineering', status: 'published', publishedDate: new Date('2024-05-10'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Quy trình bảo trì Chiller giải nhiệt nước', slug: 'bao-tri-chiller-dinh-ky', excerpt: 'Hướng dẫn các bước kiểm tra máy nén, bình ngưng.', content: '<p>Bảo trì giúp kéo dài tuổi thọ thiết bị.</p>', category: 'Chuyên ngành', featuredImageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=1200', author: 'Engineering', status: 'published', publishedDate: new Date('2024-05-11'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Phân tích chỉ số BOD, COD trong nước thải', slug: 'phan-tich-chi-so-bod-cod', excerpt: 'Hiểu các thông số để chọn phương án xử lý.', content: '<p>Mức độ ô nhiễm hữu cơ và cách xử lý.</p>', category: 'Chuyên ngành', featuredImageUrl: 'https://images.unsplash.com/photo-1543286386-713bcd534a70?q=80&w=1200', author: 'Engineering', status: 'published', publishedDate: new Date('2024-05-12'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Tính toán ống nước tiêu chuẩn TCVN', slug: 'tinh-toan-ong-nuoc-tcvn', excerpt: 'Công thức tra cứu thủy lực phục vụ thiết kế.', content: '<p>Hướng dẫn xác định lưu lượng tính toán.</p>', category: 'Chuyên ngành', featuredImageUrl: 'https://images.unsplash.com/photo-1503694978374-8a2fa686963a?q=80&w=1200', author: 'Engineering', status: 'published', publishedDate: new Date('2024-05-13'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Giải pháp chống rung máy bơm công suất lớn', slug: 'chong-rung-may-bom', excerpt: 'Sử dụng lò xo giảm chấn bảo vệ đường ống.', content: '<p>Xử lý rung động bằng khớp nối mềm.</p>', category: 'Chuyên ngành', featuredImageUrl: 'https://images.unsplash.com/photo-1517646272422-b28618214295?q=80&w=1200', author: 'Engineering', status: 'published', publishedDate: new Date('2024-05-14'), createdAt: new Date(), updatedAt: new Date() },

        // CATEGORY: Xã hội
        { id: randomUUID(), title: 'Siphonet làm sạch sông Hồng vì môi trường', slug: 'lam-sach-song-hong', excerpt: '100 nhân viên tham gia thu gom rác thải nhựa.', content: '<p>Vì hành tinh xanh, nâng cao nhận thức.</p>', category: 'Xã hội', featuredImageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=1200', author: 'Social', status: 'published', publishedDate: new Date('2024-06-01'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Mẹo tiết kiệm nước sinh hoạt hàng ngày', slug: 'tiet-kiem-nuoc-sinh-hoat', excerpt: 'Thói quen nhỏ giúp tiết kiệm hàng ngàn lít nước.', content: '<p>Tái sử dụng nước, thiết bị vệ sinh thông minh.</p>', category: 'Xã hội', featuredImageUrl: 'https://images.unsplash.com/photo-1595467793069-1aecc2cc6759?q=80&w=1200', author: 'Social', status: 'published', publishedDate: new Date('2024-06-02'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Ngày hội Hiến máu "Giọt hồng Siphonet"', slug: 'hien-mau-siphonet', excerpt: 'Lan tỏa yêu thương và trách nhiệm cộng đồng.', content: '<p>Phối hợp Viện Huyết học Trung ương.</p>', category: 'Xã hội', featuredImageUrl: 'https://images.unsplash.com/photo-1615461066841-6116ecaabb04?q=80&w=1200', author: 'Social', status: 'published', publishedDate: new Date('2024-06-03'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Trao học bổng cho sinh viên nghèo vượt khó', slug: 'hoc-bong-sinh-vien', excerpt: 'Hỗ trợ tài năng trẻ ngành kỹ thuật môi trường.', content: '<p>10 suất học bổng trị giá 50 triệu đồng.</p>', category: 'Xã hội', featuredImageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1200', author: 'Social', status: 'published', publishedDate: new Date('2024-06-04'), createdAt: new Date(), updatedAt: new Date() },
        { id: randomUUID(), title: 'Tài trợ hệ thống lọc nước RO vùng cao', slug: 'loc-nuoc-ro-vung-cao', excerpt: 'Mang nguồn nước sạch đến thầy trò Hà Giang.', content: '<p>Dự án thiện nguyện tại trường tiểu học.</p>', category: 'Xã hội', featuredImageUrl: 'https://images.unsplash.com/photo-1518398046578-8cca57732e17?q=80&w=1200', author: 'Social', status: 'published', publishedDate: new Date('2024-06-05'), createdAt: new Date(), updatedAt: new Date() }
    ]

    try {
        console.log('🔄 Executing bulk upsert...')
        await db.insert(postsTable).values(mockPosts).onConflictDoUpdate({
            target: postsTable.slug,
            set: { updatedAt: new Date() } // Just update updatedAt to trigger conflict handle correctly for existing
        }).execute()

        console.log('✅ Seeding completed successfully!')
        process.exit(0)
    } catch (error) {
        console.error('❌ Seeding failed:', error)
        process.exit(1)
    }
}

seed()
